const fs = require('fs');
const path = require('path');

const filesToTranslate = [
    'index.html',
    'acropolis-tour.html',
    'argolis-tour.html',
    'delphi-tour.html',
    'meteora-tour.html',
    'sounio-tour.html'
];

const translations = {
    // Shared
    'Taxi & Van Transfers Athens | Airport Transfers Lavrio, Lagonisi, Keratea': '雅典出租车和面包车接送 | 拉夫里奥、拉戈尼西、科拉蒂亚机场接送',
    'Premium Taxi & Van transfers in Athens, Lavrio, Lagonisi & Keratea. 24/7 Athens Airport pickups, port transfers & private tours to Acropolis, Sounio, Delphi, Meteora.': '雅典、拉夫里奥、拉戈尼西及科拉蒂亚的优质出租车和面包车接送服务。提供全天候雅典机场接机、港口接送以及卫城、苏尼翁、德尔斐、梅黛奥拉的私人游览。',
    'Services': '服务',
    'Why Choose Us': '为什么选择我们',
    'Book Now': '立即预订',
    'Home': '首页',
    'Why Us': '关于我们',
    'Quick Links': '快速链接',
    'Contact Info': '联系方式',
    'Your reliable partner for luxury transfers and tours in Greece.': '您在希腊值得信赖的豪华接送和旅游合作伙伴。',
    'All Rights Reserved.': '版权所有。',

    // index.html
    'Premium Taxi & Van Transfers in Athens & Lavrio': '雅典和拉夫里奥的优质出租车和面包车接送服务',
    '"Reliable Taxi & Luxury Van services in Lavrio, Lagonisi, and Keratea.': '“拉夫里奥、拉戈尼西和科拉蒂亚的可靠出租车和豪华面包车服务。',
    'Specialized in seamless Athens Airport pickups, port transfers, and private sightseeing tours.': '专注于无缝的雅典机场接机、港口接送和私人观光旅游。”',
    'Best way to reach us': '联系我们的最佳方式',
    'Instant replies &bull; Quick booking &bull; 24/7 available': '即时回复 &bull; 快速预订 &bull; 24/7 全天候可用',
    'Chat on WhatsApp': '通过 WhatsApp 聊天',
    'View Fleet': '查看车队',
    'Chat with us': '与我们聊天',
    'Our Premium Fleet and Services': '我们的优质车队和服务',
    'Select the perfect ride for your needs, whether you\'re traveling solo or with a group, discover Greece.': '根据您的需求选择完美的座驾，无论您是独自旅行还是结伴出游，尽情探索希腊。',
    'Executive Taxi': '行政出租车',
    'Gallery': '图库',
    'Perfect for solo travelers or couples. Fast, efficient, and comfortable city or airport transfers.': '独行旅客或情侣的理想选择。快速、高效且舒适的城市或机场接送。',
    '1-4 Passengers': '1-4 名乘客',
    '3 Standard Bags': '3个标准行李箱',
    'Free Wi-Fi': '免费无线网络',
    'Book Taxi': '预订出租车',
    'Most Popular': '最受欢迎',
    'Luxury Van': '豪华面包车',
    'Spacious travel for families, groups or sailing crews. Premium comfort with extra room for luggage.': '适合家庭、团体或航海人员的宽敞旅行。卓越的舒适感，并提供额外的行李空间。',
    '1-8 Passengers': '1-8 名乘客',
    '8-10 Bags': '8-10个行李箱',
    'Bottled Water Included': '包含瓶装水',
    'Book Van': '预订面包车',
    'Athens Airport Transfer': '雅典机场接送',
    'Direct pickup from the gate so you don\'t have to walk. Skip the long taxi lines and arrive': '直接在登机口接机，免去步行烦恼。跳过排队等候的出租车，轻松抵达目的地。',
    'stress-free. We monitor your flight.': '我们还会实时监控您的航班动态。',
    'Gate Pickup, No Walking': '登机口接机，无需步行',
    'Skip Taxi Queues': '免排队等候',
    '60m Free Wait Time': '60分钟免费等待',
    'Book Transfer': '预订接送',
    'Select Transfer Type:': '选择接送类型:',
    'Arrival (From Airport)': '到达（从机场出发）',
    'Departure (To Airport)': '出发（前往机场）',
    'Lavrio Port, Olympic Marine': '拉夫里奥港，奥林匹克码头',
    '"Seamless pickup directly from your yacht. Specialized in transfers for sailing crews with': '“直接从您的游艇无缝接载。专门为帆船船员提供大容量面包车接送，',
    'high-capacity vans for extra gear and heavy bags.': '满足额外装备和沉重行李的需求。',
    'No need to struggle finding a vehicle that fits your entire crew and equipment.': '无需费力寻找能容纳所有船员和设备的车辆。”',
    'Crew Vans Available': '提供船员专用面包车',
    'Excess Luggage Friendly': '行李额度宽松',
    'Point-to-Point Service': '点对点服务',
    'Main Ports: Piraeus, Rafina, Lavrio': '主要港口：比雷埃夫斯，拉菲纳，拉夫里奥',
    'Seamless pickup directly from your ferry, cruise ship, or hydrofoil. Skip the long taxi queues at': '直接从渡轮、游轮或水翼船无缝接载。跳过繁忙港口的排队等候，',
    'busy ports and enjoy a fixed-price transfer': '享受固定价格的接送服务，',
    'to your hotel or Athens Airport. We monitor ferry arrivals': '前往您的酒店或雅典机场。我们会实时监控渡轮到达时间。',
    'Pier-Side Pickup': '码头边接送',
    'Fixed & Upfront Pricing': '固定且透明的价格',
    'We Monitor Ferry Times': '实时监控渡轮时间',
    'Airbnb villas and hotels': 'Airbnb别墅和酒店',
    'Reliable 24/7 transfers directly to your villa, apartment, or hotel. We specialize in finding even': '全天候可靠接送，直达您的别墅、公寓或酒店。我们擅长寻找',
    'the most remote locations in Lagonisi and Keratea.': '拉戈尼西和科拉蒂亚最偏远的位置。',
    'Enjoy a stress-free arrival with a professional driver waiting for you.': '有专业司机等候，享受无忧抵达。',
    'Door-to-Door Service': '门到门服务',
    'Perfect for Families': '家庭出游的理想选择',
    'Local Area Experts': '当地专家',
    'Athens & Acropolis Tour': '雅典和卫城之旅',
    'Explore the historical heart of Greece. Full or half-day private tours of the Acropolis, Plaka, and': '探索希腊的历史中心。卫城、普拉卡等地的全天或半天私人游览。',
    'more.': '',
    'Panoramic Stops': '全景停靠点',
    '4 to 8 Hours': '4到8小时',
    'Knowledgeable Driver': '知识渊博的司机',
    'View Details': '查看详情',
    'Sounio & Temple of Poseidon': '苏尼翁和波塞冬神庙',
    'Experience the breathtaking sunset at Cape Sounio along the beautiful Athenian Riviera.': '沿着美丽的雅典海滨体验苏尼翁角令人叹为观止的日落。',
    'Coastal Scenic Drive': '沿海风景驱车',
    '4 to 5 Hours': '4到5小时',
    'Sunset Views': '日落美景',
    'Delphi & Ancient Oracle': '德尔斐和古老神谕',
    'Discover the center of the ancient world. Full-day private tour to the UNESCO World Heritage site.': '探索古代世界的中心。前往联合国教科文组织世界遗产的全天私人游览。',
    'Scenic Mountain Drive': '风景秀丽的山区驾驶',
    '8 to 10 Hours': '8到10小时',
    'Historical Ruins': '历史遗迹',
    'Meteora Monasteries': '梅黛奥拉修道院',
    'Marvel at the breathtaking rock formations and visit the spectacular cliff-top monasteries.': '惊叹于令人叹为观止的岩层，并参观壮观的悬崖顶修道院。',
    'Spectacular Views': '壮观的景色',
    'Full Day / 2 Days': '全天 / 2天',
    'Monastery Visits': '修道院参观',
    'Mycenae & Epidaurus': '迈锡尼和埃皮达鲁斯',
    'Explore the legendary Tomb of Agamemnon and the ancient theater with perfect acoustics.': '探索传奇的阿伽门农墓和拥有完美音响效果的古剧院。',
    'Ancient Theater': '古剧院',
    'Historic Ruins': '历史遗迹',
    'Why Travel With Us?': '为什么和我们一起旅行？',
    'We pride ourselves on providing a top-tier experience for every passenger.': '我们为能给每位乘客提供顶级的体验而自豪。',
    'Available 24/7': '全天候可用',
    'Day or night, our drivers are ready to pick you up whenever you need.': '无论白天还是黑夜，我们的司机随时准备接您。',
    'Fixed Pricing': '固定价格',
    'No hidden fees. Know exactly what you are paying before you book.': '没有隐藏费用。预订前确切了解您要支付的费用。',
    'English Speaking': '英语服务',
    'All our professional drivers are fluent in English and ready to assist you.': '我们所有专业的司机都能流利使用英语，并随时准备协助您。',
    'Premium Vehicles': '高级车辆',
    'Immaculately clean, air-conditioned fleet maintained to the highest standards.': '无可挑剔的干净、配有空调的车队，始终保持最高标准。',
    'Ready for a stress-free transfer?': '准备好无忧接送了吗？',
    'Contact us via WhatsApp for instant booking capability and pricing inquiries.': '通过WhatsApp联系我们进行即时预订和价格咨询。',
    'Send\n                    Email': '发送邮件',
    'Send Email': '发送邮件',
    'Vehicle Gallery': '车辆图库',
    'See how customers review us': '查看客户对我们的评价',

    // Shared tour
    'Back to all Tours': '返回所有游览',
    'Tour Overview': '游览概述',
    'What to Expect': '行程亮点',
    'Gallery': '图库',
    'Tour Details': '游览详情',
    'Price on Request': '价格另询',
    'Duration': '时长',
    'Private Tour (1-8 pax)': '私人游览（1-8人）',
    'Luxury Van or Sedan': '豪华面包车或轿车',
    'English Speaking Driver': '英语司机',
    'Entrance fees not included': '门票不含',
    'Book via WhatsApp': '通过WhatsApp预订',
    'Send an Inquiry': '发送咨询',
    'Talk to us': '联系我们',

    // Acropolis
    'Athens & Acropolis Experience': '雅典和卫城体验',
    'Discover the cradle of Western civilization. A comprehensive journey through the historical landmarks of Athens.': '发现西方文明的摇篮。一次穿越雅典历史地标的全面之旅。',
    'Join us for an unforgettable journey into the heart of ancient democracy and philosophy. This private full-day or half-day tour takes you through the most iconic monuments of the Greek capital, combining millennia of history with the vibrant modern city life.': '加入我们，进入古代民主和哲学中心度过一段难忘的旅程。这次全天或半天私人游览将带您穿梭于希腊首都最具标志性的纪念碑，将千年的历史与充满活力的现代城市生活完美结合。',
    'You will walk on the sacred rock of the Acropolis, admire the marble stadium of the first modern Olympics, and enjoy the most spectacular panoramic views of Athens from Lycabettus Hill.': '您将漫步在神圣的卫城岩石上，欣赏第一届现代奥运会的大理石体育场，并从利卡维多斯山顶欣赏雅典最壮观的全景。',
    'The Acropolis': '卫城',
    'The majestic Parthenon': '宏伟的帕特农神庙',
    'Historic Center': '历史中心',
    'Plaka and Monastiraki': '普拉卡和蒙纳斯提拉奇',
    '1. The Sacred Rock of Acropolis': '1. 神圣的卫城岩石',
    'Your private driver will pick you up from your hotel. Our first and most important stop will be the Acropolis, where you will visit the Parthenon, the Erechtheion, and the Temple of Athena Nike.': '您的私人司机将从酒店接您。我们的第一站也是最重要的一站将是卫城，您将参观帕特农神庙、伊瑞克提翁神庙和雅典娜胜利神庙。',
    '2. Temple of Olympian Zeus': '2. 奥林匹亚宙斯神庙',
    'Admire the colossal columns of one of the largest temples in the ancient world, along with Hadrian\'s Arch.': '欣赏古代世界最大神庙之一的巨大柱子，以及哈德良拱门。',
    '3. Panathenaic Stadium': '3. 泛雅典体育场',
    'See the impressive white marble stadium, the historic site of the first modern Olympic Games in 1896.': '参观令人印象深刻的白色大理石体育场，这是1896年第一届现代奥运会的历史遗址。',
    '4. Changing of the Guards': '4. 卫兵交接',
    'We will watch the traditional ceremony of the Evzones outside the Greek Parliament at Syntagma Square.': '我们将在宪法广场的希腊议会外观看传统卫兵交接仪式。',
    '5. Lycabettus Hill & Plaka': '5. 利卡维多斯山和普拉卡',
    'We will drive up Lycabettus Hill for the best panoramic view of Athens and finish with a walk in the charming Plaka neighborhood.': '我们将驱车前往利卡维多斯山欣赏雅典最佳全景，最后在迷人的普拉卡街区散步。',

    // Argolis
    'Mycenae & Epidaurus Experience': '迈锡尼和埃皮达鲁斯体验',
    'Step back into the Bronze Age and classical antiquity. A journey through the mythical Peloponnese.': '重返青铜时代和古典古代。穿越神话般的伯罗奔尼撒半岛的旅程。',
    'This full-day private tour takes you out of Athens and into the heart of the Peloponnese, exploring the rich history and myths of Argolis. Discover the remains of the Mycenaean civilization that dominated Greece in the second millennium BC.': '这次全天私人游览带您离开雅典，进入伯罗奔尼撒半岛的中心，探索阿尔戈利斯的丰富历史和神话。发现公元前两千年统治希腊的迈锡尼文明的遗迹。',
    'You will stand before the famous Lion Gate, explore the acoustic marvel of the ancient theater of Epidaurus, and stroll through the picturesque streets of Nafplio, the first capital of modern Greece.': '您将站在著名的狮子门前，探索具有惊人声学效果的埃皮达鲁斯古剧院，漫步在现代希腊第一个首都纳夫普利奥风景如画的街道上。',
    'Ancient Mycenae': '古迈锡尼',
    'Kingdom of Agamemnon': '阿伽门农王国',
    'Epidaurus': '埃皮达鲁斯',
    'The Great Theater': '宏伟的剧院',
    '1. The Corinth Canal': '1. 科林斯运河',
    'Our first stop is the breathtaking Corinth Canal, an engineering marvel connecting the Aegean and Ionian seas.': '我们的第一站是令人叹为观止的科林斯运河，这是连接爱琴海和爱奥尼亚海的工程奇迹。',
    '2. Ancient Mycenae': '2. 古迈锡尼',
    'Walk through the Lion Gate and explore the Cyclopean walls, the Royal Tombs, and the Treasury of Atreus.': '穿过狮子门，探索独眼巨人城墙、皇家陵墓和阿特柔斯宝库。',
    '3. Nafplio City': '3. 纳夫普利奥市',
    'We will visit the romantic coastal city of Nafplio, featuring Venetian architecture and the imposing Palamidi fortress. Time for a traditional Greek lunch.': '我们将参观浪漫的沿海城市纳夫普利奥，欣赏威尼斯建筑和雄伟的帕拉米迪堡垒。并享用传统的希腊午餐。',
    '4. Ancient Theater of Epidaurus': '4. 埃皮达鲁斯古剧院',
    'Experience the flawless acoustics of the best-preserved ancient Greek theater, still used for performances today.': '体验保存最完好的古希腊剧院的完美音响效果，该剧院至今仍用于演出。',

    // Delphi
    'Delphi Oracle Experience': '德尔斐神谕体验',
    'Journey to the center of the ancient world. Discover the mysteries of the Oracle of Apollo in a stunning mountain setting.': '前往古代世界的中心。在令人惊叹的山区环境中探索阿波罗神谕的奥秘。',
    'Considered the "Navel of the World" in ancient times, Delphi was the most important religious sanctuary in Greece. This full-day private tour takes you through spectacular mountain scenery to the slopes of Mount Parnassus.': '在古代被认为是“世界肚脐”的德尔斐是希腊最重要的宗教圣地。这次全天私人游览将带您穿过壮观的山区风景，到达帕纳塞斯山坡。',
    'You will explore the ruins of the Temple of Apollo where the Pythia delivered her famous prophecies, admire masterpieces of ancient art in the museum, and visit the beautiful traditional mountain village of Arachova.': '您将探索阿波罗神庙遗址，皮提亚曾在那里发表著名的预言，在博物馆里欣赏古代艺术的杰作，并参观美丽传统的山区村庄阿拉霍瓦。',
    'Temple of Apollo': '阿波罗神庙',
    'The Ancient Oracle': '古老神谕',
    'Delphi Museum': '德尔斐博物馆',
    'Ancient Masterpieces': '古代杰作',
    '1. Drive through Boeotia': '1. 驱车穿过维奥蒂亚',
    'We start with a scenic drive through the fertile plains of Boeotia, passing the towns of Thebes and Levadia.': '我们从维奥蒂亚肥沃的平原开始风景如画的驾驶，途经底比斯和莱瓦迪亚镇。',
    '2. Arachova Village': '2. 阿拉霍瓦村',
    'A short stop at the picturesque mountain village of Arachova, famous for its hand-woven carpets and traditional cheese.': '在风景如画的山区小镇阿拉霍瓦短暂停留，以其手工编织的地毯和传统奶酪而闻名。',
    '3. Archaeological Site of Delphi': '3. 德尔斐考古遗址',
    'Walk the Sacred Way, see the Athenian Treasury, and stand before the ruins of the Temple of Apollo where the Oracle spoke.': '走在神圣之路上，看雅典人的金库，并站在阿波罗神庙遗址前，那里曾是神谕宣示的地方。',
    '4. Delphi Archaeological Museum': '4. 德尔斐考古博物馆',
    'Admire world-class artifacts including the famous Charioteer of Delphi, the Sphinx of Naxos, and the Twin Kouroi.': '欣赏世界级的文物，包括著名的德尔斐战车御者、纳克索斯的斯芬克斯和双胞胎库罗斯。',

    // Meteora
    'Meteora Monasteries Experience': '梅黛奥拉修道院体验',
    'Witness a geological miracle. Explore the Byzantine monasteries suspended in the air on giant rock pillars.': '见证地质奇迹。探索悬浮在巨大石柱上的拜占庭修道院。',
    'Meteora is one of the most spectacular and extraordinary landscapes in the world. This tour takes you to the heart of mainland Greece to witness giant sandstone rock pillars rising hundreds of meters into the sky, crowned by historic Orthodox monasteries.': '梅黛奥拉是世界上最壮观非凡的景观之一。这次游览将带您深入希腊大陆的心脏，见证数百米高直插云霄的巨大砂岩石柱，以及顶部的历史悠久的东正教修道院。',
    'A UNESCO World Heritage site, Meteora offers a unique combination of natural beauty and spiritual heritage. We offer this as a long full-day tour or a relaxed 2-day overnight experience.': '作为联合国教科文组织世界遗产，梅黛奥拉提供了自然美景和精神遗产的独特结合。我们提供较长的一日游或轻松的两日游住宿体验。',
    'The Monasteries': '修道院',
    'Suspended in the air': '悬浮在空中',
    'Natural Wonder': '自然奇观',
    'Giant Rock Formations': '巨大的岩石群',
    '1. Journey through Central Greece': '1. 穿越希腊中部之旅',
    'A comfortable drive through the Greek countryside, passing the plains of Thessaly and the cities of Lamia and Trikala.': '舒适地驱车穿过希腊乡村，途经色萨利平原以及拉米亚和特里卡拉市。',
    '2. Kalambaka Town': '2. 卡兰巴卡镇',
    'Arrival at the town of Kalambaka, located at the very base of the majestic Meteora rocks. Time for a traditional lunch.': '抵达卡兰巴卡镇，位于雄伟的梅黛奥拉岩石脚下。享用传统午餐。',
    '3. Monastery Visits': '3. 修道院参观',
    'We will drive up the winding roads to visit 2 or 3 of the remaining active monasteries (such as Great Meteoron, Varlaam, or Holy Trinity).': '我们将驱车沿蜿蜒的道路参观现存的2或3座活跃修道院（如大梅黛奥拉修道院、瓦尔拉姆修道院或圣三一修道院）。',
    '4. Panoramic Photo Stops': '4. 全景摄影停靠点',
    'We will make multiple stops at the best viewpoints so you can capture the breathtaking landscape and sunset.': '我们将在最佳观景点进行多次停靠，让您捕捉令人叹为观止的风景和日落。',

    // Sounio
    'Cape Sounio Sunset Experience': '苏尼翁角日落体验',
    'Drive along the beautiful Athenian Riviera and witness a magical sunset at the Temple of Poseidon.': '沿着美丽的雅典海滨驱车，并在波塞冬神庙见证神奇的日落。',
    'Escape the bustling city and enjoy a relaxing half-day tour along the scenic coastal road of the Athenian Riviera. Cape Sounio, the southernmost tip of the Attica peninsula, offers breathtaking views over the Aegean Sea.': '逃离繁华的城市，沿着雅典海滨沿海风景秀丽的道路享受轻松的半日游。苏尼翁角位于阿提卡半岛的最南端，享有爱琴海令人叹为观止的美景。',
    'Perched on the edge of the cliff stands the magnificent Temple of Poseidon, the ancient Greek god of the sea. Watching the sun dip below the horizon from this mythological vantage point is an unforgettable experience.': '雄伟的波塞冬神庙，古希腊海神，坐落在悬崖的边缘。从这个神话般的有利位置观看太阳沉入地平线以下将是一次难忘的体验。',
    'Temple of Poseidon': '波塞冬神庙',
    'Ancient Sea God': '古代海神',
    'Athenian Riviera': '雅典海滨',
    'Scenic Coastal Drive': '风景秀丽的沿海驾驶',
    '1. The Athenian Riviera': '1. 雅典海滨',
    'Enjoy a scenic coastal drive passing through the upscale suburbs of Glyfada, Voula, and Vouliagmeni.': '享受一段风景秀丽的沿海驾驶，途经格利法达、武拉和武利亚格梅尼的高档郊区。',
    '2. Lake Vouliagmeni': '2. 武利亚格梅尼湖',
    'A short stop at the hidden geological treasure of Lake Vouliagmeni, famous for its thermal waters and stunning rock walls.': '在武利亚格梅尼湖的隐秘地质宝藏短暂停留，该湖以温泉水和令人惊叹的岩壁而闻名。',
    '3. Cape Sounio': '3. 苏尼翁角',
    'Arrival at the dramatic cliffs of Cape Sounio where the ancient Greeks built their monument to the god of the sea.': '抵达苏尼翁角的壮观悬崖，古希腊人在这里建造了纪念海神的纪念碑。',
    '4. The Sunset': '4. 日落',
    'Explore the ruins of the Temple of Poseidon and watch one of the most famous and romantic sunsets in Greece.': '探索波塞冬神庙遗址，并观看希腊最著名、最浪漫的日落之一。'
};

filesToTranslate.forEach(file => {
    const enPath = path.join(__dirname, file);
    const zhPath = path.join(__dirname, 'zh', file);
    
    if (fs.existsSync(enPath)) {
        let content = fs.readFileSync(enPath, 'utf8');

        // Regex replace translations
        Object.keys(translations).forEach(eng => {
            const zh = translations[eng];
            // Escape special characters in English string to safely use in regex
            // But doing split/join is safer for exact matches
            content = content.split(eng).join(zh);
        });

        // Set the proper language attribute
        content = content.replace(/<html lang="en">/, '<html lang="zh-CN">');
        
        fs.writeFileSync(zhPath, content, 'utf8');
        console.log(`Translated ${file} to zh`);
    }
});
