// SEO Fix V2 - Part 1: Data definitions
// This file exports SEO data for all languages
const base='https://taxiathenstransfers.com';
const langs=['en','de','fr','es','it','pt','pl','el','he','no','zh','ja','hu','ru'];
const dirs= ['','de','fr','es','it','pt','pl','el','he','no','zh','ja','hu','ru'];
const hreflangs=['en','de','fr','es','it','pt','pl','el','he','nb','zh','ja','hu','ru'];
const pages=['index.html','acropolis-tour.html','argolis-tour.html','delphi-tour.html','meteora-tour.html','sounio-tour.html'];
const locales={en:'en_GB',de:'de_DE',fr:'fr_FR',es:'es_ES',it:'it_IT',pt:'pt_PT',pl:'pl_PL',el:'el_GR',he:'he_IL',no:'nb_NO',zh:'zh_CN',ja:'ja_JP',hu:'hu_HU',ru:'ru_RU'};

const titles={
en:{'index.html':'Taxi & Van Transfers Athens | Airport Transfers Lavrio, Lagonisi, Keratea','acropolis-tour.html':'Athens & Acropolis Private Tour | Taxi & Van Transfers','argolis-tour.html':'Mycenae & Epidaurus Private Tour | Taxi & Van Transfers','delphi-tour.html':'Delphi & Ancient Oracle Private Tour | Taxi & Van Transfers','meteora-tour.html':'Meteora Monasteries Private Tour | Taxi & Van Transfers','sounio-tour.html':'Cape Sounio & Temple of Poseidon Tour | Taxi & Van Transfers'},
de:{'index.html':'Taxi & Van Transfers Athen | Flughafentransfer Lavrio, Lagonisi, Keratea','acropolis-tour.html':'Athen & Akropolis Privattour | Taxi & Van Transfers','argolis-tour.html':'Mykene & Epidaurus Privattour | Taxi & Van Transfers','delphi-tour.html':'Delphi & Antikes Orakel Privattour | Taxi & Van Transfers','meteora-tour.html':'Meteora-Klöster Privattour | Taxi & Van Transfers','sounio-tour.html':'Kap Sounio & Poseidontempel Tour | Taxi & Van Transfers'},
fr:{'index.html':'Transferts Taxi & Van Athènes | Aéroport Lavrio, Lagonisi, Keratea','acropolis-tour.html':'Visite Privée Athènes & Acropole | Taxi & Van Transfers','argolis-tour.html':'Visite Privée Mycènes & Épidaure | Taxi & Van Transfers','delphi-tour.html':'Visite Privée Delphes & Oracle Antique | Taxi & Van Transfers','meteora-tour.html':'Visite Privée Monastères des Météores | Taxi & Van Transfers','sounio-tour.html':'Visite Cap Sounion & Temple de Poséidon | Taxi & Van Transfers'},
es:{'index.html':'Taxi & Van Transfers Atenas | Traslados Aeropuerto Lavrio, Lagonisi','acropolis-tour.html':'Tour Privado Atenas & Acrópolis | Taxi & Van Transfers','argolis-tour.html':'Tour Privado Micenas & Epidauro | Taxi & Van Transfers','delphi-tour.html':'Tour Privado Delfos & Oráculo Antiguo | Taxi & Van Transfers','meteora-tour.html':'Tour Privado Monasterios de Meteora | Taxi & Van Transfers','sounio-tour.html':'Tour Cabo Sunión & Templo de Poseidón | Taxi & Van Transfers'},
it:{'index.html':'Taxi & Van Transfers Atene | Trasferimenti Aeroporto Lavrio, Lagonisi','acropolis-tour.html':'Tour Privato Atene & Acropoli | Taxi & Van Transfers','argolis-tour.html':'Tour Privato Micene & Epidauro | Taxi & Van Transfers','delphi-tour.html':'Tour Privato Delfi & Oracolo Antico | Taxi & Van Transfers','meteora-tour.html':'Tour Privato Monasteri di Meteora | Taxi & Van Transfers','sounio-tour.html':'Tour Capo Sounion & Tempio di Poseidone | Taxi & Van Transfers'},
pt:{'index.html':'Taxi & Van Transfers Atenas | Transferências Aeroporto Lavrio, Lagonisi','acropolis-tour.html':'Tour Privado Atenas & Acrópole | Taxi & Van Transfers','argolis-tour.html':'Tour Privado Micenas & Epidauro | Taxi & Van Transfers','delphi-tour.html':'Tour Privado Delfos & Oráculo Antigo | Taxi & Van Transfers','meteora-tour.html':'Tour Privado Mosteiros de Meteora | Taxi & Van Transfers','sounio-tour.html':'Tour Cabo Súnion & Templo de Poseidon | Taxi & Van Transfers'},
pl:{'index.html':'Taxi & Van Transfers Ateny | Transfery Lotniskowe Lavrio, Lagonisi','acropolis-tour.html':'Prywatna Wycieczka Ateny & Akropol | Taxi & Van Transfers','argolis-tour.html':'Prywatna Wycieczka Mykeny & Epidauros | Taxi & Van Transfers','delphi-tour.html':'Prywatna Wycieczka Delfy & Starożytna Wyrocznia | Taxi & Van Transfers','meteora-tour.html':'Prywatna Wycieczka Klasztory Meteory | Taxi & Van Transfers','sounio-tour.html':'Wycieczka Przylądek Sunion & Świątynia Posejdona | Taxi & Van Transfers'},
el:{'index.html':'Taxi & Van Μεταφορές Αθήνα | Μεταφορές Αεροδρόμιο Λαύριο, Λαγονήσι, Κερατέα','acropolis-tour.html':'Ιδιωτική Περιήγηση Αθήνα & Ακρόπολη | Taxi & Van Transfers','argolis-tour.html':'Ιδιωτική Περιήγηση Μυκήνες & Επίδαυρος | Taxi & Van Transfers','delphi-tour.html':'Ιδιωτική Περιήγηση Δελφοί & Αρχαίο Μαντείο | Taxi & Van Transfers','meteora-tour.html':'Ιδιωτική Περιήγηση Μονές Μετεώρων | Taxi & Van Transfers','sounio-tour.html':'Περιήγηση Σούνιο & Ναός Ποσειδώνα | Taxi & Van Transfers'},
he:{'index.html':'Taxi & Van Transfers אתונה | העברות שדה תעופה לבריו, לגוניסי','acropolis-tour.html':'סיור פרטי אתונה ואקרופוליס | Taxi & Van Transfers','argolis-tour.html':'סיור פרטי מיקנה ואפידאורוס | Taxi & Van Transfers','delphi-tour.html':'סיור פרטי דלפי והאורקל העתיק | Taxi & Van Transfers','meteora-tour.html':'סיור פרטי מנזרי מטאורה | Taxi & Van Transfers','sounio-tour.html':'סיור כף סוניון ומקדש פוסידון | Taxi & Van Transfers'},
no:{'index.html':'Taxi & Van Transfers Athen | Flyplasstransport Lavrio, Lagonisi, Keratea','acropolis-tour.html':'Privat Tur Athen & Akropolis | Taxi & Van Transfers','argolis-tour.html':'Privat Tur Mykene & Epidaurus | Taxi & Van Transfers','delphi-tour.html':'Privat Tur Delfi & Det Gamle Orakelet | Taxi & Van Transfers','meteora-tour.html':'Privat Tur Meteora-klostrene | Taxi & Van Transfers','sounio-tour.html':'Tur Kapp Sounion & Poseidons Tempel | Taxi & Van Transfers'},
zh:{'index.html':'雅典出租车和面包车接送 | 拉夫里奥、拉戈尼西、科拉蒂亚机场接送','acropolis-tour.html':'雅典和卫城私人游览 | 雅典出租车和面包车接送','argolis-tour.html':'迈锡尼和埃皮达鲁斯私人游览 | 雅典出租车和面包车接送','delphi-tour.html':'德尔斐和古老神谕私人游览 | 雅典出租车和面包车接送','meteora-tour.html':'梅黛奥拉修道院私人游览 | 雅典出租车和面包车接送','sounio-tour.html':'苏尼翁角和波塞冬神庙游览 | 雅典出租车和面包车接送'},
ja:{'index.html':'アテネのタクシー＆バン送迎 | ラブリオ、ラゴニシ、ケラテアの空港送迎','acropolis-tour.html':'アテネとアクロポリス プライベートツアー | タクシー＆バン送迎','argolis-tour.html':'ミケーネとエピダウロス プライベートツアー | タクシー＆バン送迎','delphi-tour.html':'デルフィと古代の神託 プライベートツアー | タクシー＆バン送迎','meteora-tour.html':'メテオラ修道院 プライベートツアー | タクシー＆バン送迎','sounio-tour.html':'スニオン岬とポセイドン神殿ツアー | タクシー＆バン送迎'},
hu:{'index.html':'Taxi & Van Transzfer Athén | Reptéri Transzfer Lavrio, Lagonisi, Keratea','acropolis-tour.html':'Athén & Akropolisz Privát Túra | Taxi & Van Transfers','argolis-tour.html':'Mükéné & Epidaurusz Privát Túra | Taxi & Van Transfers','delphi-tour.html':'Delfi & Ókori Jósda Privát Túra | Taxi & Van Transfers','meteora-tour.html':'Meteora Kolostorok Privát Túra | Taxi & Van Transfers','sounio-tour.html':'Szunion-fok & Poszeidón Templom Túra | Taxi & Van Transfers'},
ru:{'index.html':'Такси и Вэн Трансферы Афины | Трансфер из Аэропорта Лаврио, Лагониси, Кератея','acropolis-tour.html':'Частный тур по Афинам и Акрополю | Taxi & Van Transfers','argolis-tour.html':'Частный тур в Микены и Эпидавр | Taxi & Van Transfers','delphi-tour.html':'Частный тур в Дельфы и Древний Оракул | Taxi & Van Transfers','meteora-tour.html':'Частный тур в Монастыри Метеоры | Taxi & Van Transfers','sounio-tour.html':'Тур на мыс Сунион и Храм Посейдона | Taxi & Van Transfers'}
};

module.exports={base,langs,dirs,hreflangs,pages,locales,titles};
